@baseUrl = http://localhost:3333

### Register
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "name": "Viny Bergamo",
  "email": "vinybergamo@gmail.com",
  "password": "123456"
}

### Login
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "vinybergamo@gmail.com",
  "password": "123456"
}
### Capture Token
@token = {{login.response.body.token}}

### List Orders
GET {{baseUrl}}/orders?limit=1
Authorization: Bearer {{token}}

### Create Order
# @name createOrder
POST {{baseUrl}}/orders
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "lab": "Lab 1",
  "patient": "Patient 1",
  "customer": "Customer 1",
  "services": [
    {
      "name": "Service 1",
      "value": 10
    }
  ]
}

### Capture Order ID
@order_id = {{createOrder.response.body._id}}

### Advance Order
PATCH {{baseUrl}}/orders/{{order_id}}/advance
Authorization: Bearer {{token}}
